apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  type: LoadBalancer  
    ports:
      - port: 9090
        targetPort: prometheus-port
  selector: 
    app: prometheus-server
  